[package]
name = "rpp-parser"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Parser for Reaper's RPP project files"
homepage = "https://github.com/Cloud-Scythe-Labs/rpp-parser"
repository = "https://github.com/Cloud-Scythe-Labs/rpp-parser"

[dependencies]
nom = "7.1.3"
serde = { version = "1", features = ["derive"] }
